language: java
dist: trusty
sudo: false # faster builds

# safelist
branches:
  only:
  - master
  - dev

env:
  global:
    - DEV_BRANCH=dev
    - RELEASE_BRANCH=master
    - REPO=ebx/ebx-distributedratelimiters-sdk
    - NO_COLOUR='\033[0m'
    - RED_COLOUR='\033[0;31m'
    - GREEN_COLOUR='\033[0;32m'

before_script:
  - export SOURCE_BRANCH_NAME=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi) 
  - echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import || echo "Failed to import GPG_SECRET_KEYS (probably because this branch is a PR)."
  - echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust || echo "Failed to import GPG_OWNERTRUST (probably because this branch is a PR)."
  - source Infrastructure/Build-Scripts/export_mvn_version.sh
  - source Infrastructure/Build-Scripts/validate_build.sh

script:
  - source Infrastructure/Build-Scripts/build_sdk_travis.sh
  
after_failure:
  - cat target/surefire-reports/*.txt

## Prepare the release for Github
## Ensure we have a suitable git tag for the release based on the verison number
before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "MarcFletcher"
  - git config --local user.email "marc@echobox.com"
  - export DEPLOY_TAG=v$MVN_VERSION
  - git tag $DEPLOY_TAG
  
## Create the release in Github
deploy:
  provider: releases
  api_key:
    secure: R+aGMyde1OrcyhP2rkPz4q0OEcMM9hHeu/Balo0Y8NiuvoGuUaYFaQdEg/N2Qi90ki/5rxChuKUaTGDtCWEqYi8dLgvcmXUwvhaOwsvZl+24ucInJkaXNnRD3oVxNTsw8PaCNPZzY1xFfARXWna250jjA1TMlVT7ACraQ4xBUxOGwtvHRIb2T7v5DsWN36wUALok3FK/QunUX8Uq89G/gsylXISdxG0fG/Hopbxi6HJ/ZBOGp0qCUQgvpsLP+IZAX0aRqyrWRF2BmtsiqP+yRS7Mi+JwVlJBDgD6JmmePNh4BrzL2MjyvoKaHyUup7jwdtngIQSE77Hj82MClnjN7mYd9egDFf6tEPCqkNjRw9NtD7gNVDPaiAonERw2YjE2dHmXX8DFX4KohPUo7elpx2uMHvbprrZFIC1/jtjJ/VrDm2XxPHceFSJdguE0A2y6Bzz1UuuJpsCpHY1XV76erWU70kLh7u6PUcROT3eWohswQjKvOHZM+2F/MH05gwTN4pNs7IDUvZ3Koo31M7dI/qBEnZYgm9SzAZn+zVbkQzYuBZ4BDltLLO8ijVL9ZWnwh3CDCjM9A1G6qY9pMEI158H+uPSzC92mhtR45oB/yyGt0e8K6AnSSHHXEHglANmxULoC1RD57sYx+ejXdqlVGcsG3VqKcd/MmyfcmdGHUnY=
  file: 
    - target/ebx-distributedratelimiters-sdk-parent-1.0.1.pom
    - DistributedRateLimiters/target/ebx-distributedratelimiters-sdk-$MVN_VERSION.jar
    - DistributedRateLimiters/target/ebx-distributedratelimiters-sdk-$MVN_VERSION-javadoc.jar
    - DistributedRateLimiters/target/ebx-distributedratelimiters-sdk-$MVN_VERSION-sources.jar
  edge: true
  on:
    repo: $REPO
    branch: $RELEASE_BRANCH
  name: v$MVN_VERSION
  
cache:
  directories:
    - ~/.m2/repository
